server:
  port: 8080
  error:
    include-message: always
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: swap
      username: szerszu
      password: szerszu
      uri: mongodb://szerszu:szerszu@localhost:27017/swap?authSource=admin
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: pl.com.pszerszenowicz.model.ProductInfoDeserializer
      group-id: repliesGroup
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer