server:
  port: 8080
  error:
    include-message: always
spring:
  data:
    mongodb:
      user: szerszu
      password: szerszu
      uri: mongodb://localhost:27017/scans
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: pl.com.pszerszenowicz.model.ProductInfoDeserializer
      group-id: repliesGroup
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer